color0 #f6dbe8
color1 #ba1a1a
color2 #a62884
color3 #874a71
color4 #af2e27
color5 #ffaede
color6 #fcb0dc
color7 #23191e
color8 #87717c
color9 #ba1a1a
color10 #a62884
color11 #874a71
color12 #af2e27
color13 #ffaede
color14 #fcb0dc
color15 #23191e

cursor                #23191e
cursor_text_color     #fff8f9
background            #fff8f9
foreground            #23191e
selection_foreground  #54414c
selection_background  #f6dbe8
active_border_color   #a62884
inactive_border_color #f6dbe8
url_color             #a62884

active_tab_foreground   #ffffff
active_tab_background   #a62884
inactive_tab_foreground #54414c
inactive_tab_background #f6dbe8
cursor_trail_color      #54414c
