# TuxBox Profile
# Profile: TuxBox GUI
# Exported: 2026-05-26 23:34:22

[profile]
name = TuxBox GUI
app_id = tuxbox-gui
window_class = tuxbox-gui

[mappings]
c1 = KEY_LEFTCTRL+KEY_LEFTALT+KEY_LEFTSHIFT+KEY_F5
c2 = KEY_LEFTCTRL+KEY_LEFTALT+KEY_LEFTSHIFT+KEY_F6
dial_ccw = KEY_LEFTCTRL+KEY_LEFTALT+KEY_LEFTSHIFT+KEY_7
dial_click = KEY_LEFTCTRL+KEY_LEFTALT+KEY_LEFTSHIFT+KEY_8
dial_cw = KEY_LEFTCTRL+KEY_LEFTALT+KEY_LEFTSHIFT+KEY_6
dpad_down = KEY_LEFTCTRL+KEY_LEFTALT+KEY_LEFTSHIFT+KEY_F9
dpad_left = KEY_LEFTCTRL+KEY_LEFTALT+KEY_LEFTSHIFT+KEY_F10
dpad_right = KEY_LEFTCTRL+KEY_LEFTALT+KEY_LEFTSHIFT+KEY_F11
dpad_up = KEY_LEFTCTRL+KEY_LEFTALT+KEY_LEFTSHIFT+KEY_F8
knob_ccw = KEY_LEFTCTRL+KEY_LEFTALT+KEY_LEFTSHIFT+KEY_4
knob_click = KEY_LEFTCTRL+KEY_LEFTALT+KEY_LEFTSHIFT+KEY_5
knob_cw = KEY_LEFTCTRL+KEY_LEFTALT+KEY_LEFTSHIFT+KEY_3
scroll_click = KEY_LEFTCTRL+KEY_LEFTALT+KEY_LEFTSHIFT+KEY_2
scroll_down = KEY_LEFTCTRL+KEY_LEFTALT+KEY_LEFTSHIFT+KEY_1
scroll_up = KEY_LEFTCTRL+KEY_LEFTALT+KEY_LEFTSHIFT+KEY_F12
short = KEY_LEFTCTRL+KEY_LEFTALT+KEY_LEFTSHIFT+KEY_F4
side = KEY_LEFTCTRL+KEY_LEFTALT+KEY_LEFTSHIFT+KEY_F1
tall = KEY_LEFTCTRL+KEY_LEFTALT+KEY_LEFTSHIFT+KEY_F3
top = KEY_LEFTCTRL+KEY_LEFTALT+KEY_LEFTSHIFT+KEY_F2
tour = KEY_LEFTCTRL+KEY_LEFTALT+KEY_LEFTSHIFT+KEY_F7
